spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
 
 routes:
 - id: CartMS
   uri: lb://CartMS
   predicates:
   - Path=/customercart-api/customer/*/product/**,/customercart-api/customer/*/products,/customercart-api/products
 - id: CustomerMS
   uri: lb://CustomerMS
   predicates: 
   - Path=/customer-api/customercarts/add-product,/customerorder-api/customer/*/orders,/customerorder-api/**
 - id: PaymentMS
   uri: lb://PaymentMS
   predicates:
   - Path=/payment-api/customer/*/card-type/**,/payment-api/customer/*/pay-order
 - id: ProductMS
   uri: lb://ProductMS
   predicates: 
   - Path=/product-api/**
